DROP SCHEMA IF EXISTS dbtbl_0_master;
DROP SCHEMA IF EXISTS dbtbl_1_master;


CREATE SCHEMA IF NOT EXISTS dbtbl_0_master;
CREATE SCHEMA IF NOT EXISTS dbtbl_1_master;

CREATE TABLE IF NOT EXISTS dbtbl_0_master.t_order_0 (id BIGINT NOT NULL AUTO_INCREMENT,order_id BIGINT NOT NULL, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS dbtbl_0_master.t_order_1 (id BIGINT NOT NULL AUTO_INCREMENT,order_id BIGINT NOT NULL, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS dbtbl_0_master.t_order_2 (id BIGINT NOT NULL AUTO_INCREMENT,order_id BIGINT NOT NULL, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS dbtbl_0_master.t_order_3 (id BIGINT NOT NULL AUTO_INCREMENT,order_id BIGINT NOT NULL, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS dbtbl_1_master.t_order_0 (id BIGINT NOT NULL AUTO_INCREMENT,order_id BIGINT NOT NULL, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS dbtbl_1_master.t_order_1 (id BIGINT NOT NULL AUTO_INCREMENT,order_id BIGINT NOT NULL, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS dbtbl_1_master.t_order_2 (id BIGINT NOT NULL AUTO_INCREMENT,order_id BIGINT NOT NULL, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS dbtbl_1_master.t_order_3 (id BIGINT NOT NULL AUTO_INCREMENT,order_id BIGINT NOT NULL, user_id INT NOT NULL, status VARCHAR(50), PRIMARY KEY (id));

